Repository plutomi/plutomi, pull requests merged in 2021-11, with the labels that each got.

#256 chore: Added a more detailed fargate template
  README.md
  bin/plutomi.ts
  cdk.json
  lib/APIStack.ts
  lib/PlutomiWebsiteStack.ts
  package-lock.json
  package.json
  pages/api/test.ts
  tsconfig.json
  yarn.lock
Labels: chore

#268 chore: created base dynamo mapping #237
  .gitignore
  newTypes.d.ts
  package-lock.json
  yarn.lock
Labels: chore

#286 chore: Simplified inputs for services
  Adapters/ApplicantsService.ts
  Adapters/AuthService.ts
  Adapters/InvitesService.ts
  Adapters/OpeningsService.ts
  Adapters/OrgsService.ts
  Adapters/PublicInfoService.ts
  Adapters/QuestionsService.ts
  Adapters/StagesService.ts
  Adapters/UsersService.ts
  SWR/useAllApplicantsInStage.ts
  SWR/useAllPublicOpenings.ts
  SWR/useAllStageQuestions.ts
  SWR/useAllStagesInOpening.ts
  SWR/useApplicantById.ts
  SWR/useOpeningById.ts
  SWR/useOrgInvites.ts
  SWR/useOrgUsers.ts
  SWR/usePrivateOrgById.ts
  SWR/usePublicApplicant.ts
  SWR/usePublicOpeningById.ts
  SWR/usePublicOrgById.ts
  SWR/usePublicStageById.ts
  SWR/useStageById.ts
  components/Applicants/ApplicantProfileModal.tsx
  components/Dashboard/DashboardContent.tsx
  components/Invites/InvitesContent.tsx
  components/Login.tsx
  components/LoginHomepage.tsx
  components/Openings/OpeningSettingsContent.tsx
  components/Openings/OpeningSettingsHeader.tsx
  components/Openings/OpeningsContent.tsx
  components/Questions/QuestionList.tsx
  components/StageReorderColumn.tsx
  components/Stages/StagesSettingsContent.tsx
  components/Team/TeamContent.tsx
  pages/openings/[opening_id]/stages/[stage_id]/settings.tsx
  pages/profile.tsx
Labels: chore

#328 chore: Login links use seals instead of relying on Dynamo for expirations
  SWR/useSelf.ts
  components/CreateOrgModal.tsx
  components/Login.tsx
  components/LoginHomepage.tsx
  defaults.ts
  middleware/withSession.ts
  next.config.js
  pages/api/auth/login.ts
  pages/api/invites/[inviteId]/index.ts
  pages/api/invites/index.ts
  pages/api/orgs/index.ts
  pages/api/users/[userId]/index.ts
  pages/api/users/[userId]/invites/index.ts
  pages/api/users/self.ts
  types/dynamo.d.ts
  types/main.d.ts
  utils/loginLinks/createLoginEventAndDeleteLoginLink.ts
  utils/loginLinks/createLoginLink.ts
  utils/loginLinks/deleteLoginLink.ts
  utils/loginLinks/getLatestLoginLink.ts
  utils/loginLinks/updateLoginLink.ts
  utils/orgs/createAndJoinOrg.ts
  utils/users/createLoginEvent.ts
  utils/users/createUser.ts
  utils/users/getUserById.ts
Labels: chore

#329 fix: Team page not showing all users in org, fix orgId not found
  pages/api/orgs/[orgId]/index.ts
  pages/api/orgs/[orgId]/users.ts
Labels: bug

#330 fix: Users being able to spam login links (bug with Time wrapper)
  pages/api/auth/login.ts
  utils/time.ts
Labels: bug

#332 feat: Added DynamoDB to the deployment stack
  bin/plutomi.ts
  lib/DynamoDBStack.ts
Labels: enhancement

#388 :book: docs: Added DynamoDB schema & NoSQL Workbench examples
  .github/semantic.yml
  README.md
  Schema/CloudFormation.json
  Schema/GSI_Plutomi_GSI1.png
  Schema/GSI_Plutomi_GSI2.png
  Schema/NoSQLWorkbench.json
  Schema/Plutomi.png
  Schema/README.md
Labels: 📖 docs
